config/routes.rb
EzPark::Application.routes.draw do
  resources :requests

  resources :meters

  resources :blocks

end

app/models/block.rb
class Block < ActiveRecord::Base
	has_many :meters
end

app/models/meter.rb
class Meter < ActiveRecord::Base
	belongs_to :block
	has_many :requests
end

app/models/request.rb
class Request < ActiveRecord::Base
	belongs_to :meter
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :null_session
  skip_before_filter :verify_authenticity_token
end

app/controllers/blocks_controller.rb
class BlocksController < ApplicationController
  before_action :set_block, only: [:show, :edit, :update, :destroy]
  respond_to :json

  # GET /blocks
  # GET /blocks.json
  def index
    # @block = Block.all
    d_lat = 0.001
    d_lon = 0.001
    if (params.has_key?(:limit))
      limit = params[:limit]
    else
      limit = 10
    end

    
    if (params.has_key?(:adminview))
      @blocks = Block.where("count > 0")
    elsif (params.has_key?(:address))
      address = params[:address]
      @blocks = Block.where("address = ?", address)
    elsif (params.has_key?(:lat) and params.has_key?(:lon))
      lat_max = params[:lat].to_f + d_lat
      lat_min = params[:lat].to_f - d_lat
      lon_max = params[:lon].to_f + d_lon
      lon_min = params[:lon].to_f - d_lon
      if (params.has_key?(:status))
        status = params[:status]
        @blocks = Block.where("lat between ? AND ? AND lon between ? AND ? AND status = ?", lat_min,
          lat_max, lon_min, lon_max, status).limit(limit)
      else
        @blocks = Block.where("lat between ? AND ? AND lon between ? AND ?", lat_min,
          lat_max, lon_min, lon_max).limit(limit)
      end
    elsif (params.has_key?(:status))
      @blocks = Block.where("status = ?", status).limit(limit)
    else
      @blocks = Block.all.limit(limit)
    end
    
  end

  # GET /blocks/1
  # GET /blocks/1.json
  def show
  end

  # GET /blocks/new
  def new
    @block = Block.new
  end

  # GET /blocks/1/edit
  def edit
  end

  # POST /blocks
  # POST /blocks.json
  def create
    @block = Block.new(block_params)

    respond_to do |format|
      if @block.save
        format.html { redirect_to @block, notice: 'Block was successfully created.' }
        format.json { render action: 'show', status: :created, location: @block }
      else
        format.html { render action: 'new' }
        format.json { render json: @block.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blocks/1
  # PATCH/PUT /blocks/1.json
  def update
    respond_to do |format|
      if @block.update(block_params)
        format.html { redirect_to @block, notice: 'Block was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @block.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blocks/1
  # DELETE /blocks/1.json
  def destroy
    @block.destroy
    respond_to do |format|
      format.html { redirect_to blocks_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_block
      @block = Block.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def block_params
      params.require(:block).permit(:address, :lat, :lon, :rate, :limit, :count, :fromDay, :toDay, :fromHour, :toHour, :status)
    end
end

app/controllers/meters_controller.rb
class MetersController < ApplicationController
  before_action :set_meter, only: [:show, :edit, :update, :destroy]

  # GET /meters
  # GET /meters.json
  def index
      max = 6700
      dmax = 50
      n = 20
      b = (5060..max).to_a.shuffle[0,n]
      c = (1..dmax).to_a.shuffle[0,n]
      t = 0

      b.each do |bid|
        block = Block.find(bid)
        block.count = c[t] - 10
        t = (t + 1)%dmax
        block.save
      end
    @meters = Meter.all
  end

  # GET /meters/1
  # GET /meters/1.json
  def show
  end

  # GET /meters/new
  def new
    @meter = Meter.new
  end

  # GET /meters/1/edit
  def edit
  end

  # POST /meters
  # POST /meters.json
  def create
    @meter = Meter.new(meter_params)

    respond_to do |format|
      if @meter.save
        format.html { redirect_to @meter, notice: 'Meter was successfully created.' }
        format.json { render action: 'show', status: :created, location: @meter }
      else
        format.html { render action: 'new' }
        format.json { render json: @meter.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /meters/1
  # PATCH/PUT /meters/1.json
  def update
    respond_to do |format|
      if @meter.update(meter_params)
        format.html { redirect_to @meter, notice: 'Meter was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @meter.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /meters/1
  # DELETE /meters/1.json
  def destroy
    @meter.destroy
    respond_to do |format|
      format.html { redirect_to meters_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_meter
      @meter = Meter.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def meter_params
      params.require(:meter).permit(:lat, :long, :block_id, :meter_number, :rate, :status)
    end
end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
  before_action :set_request, only: [:show, :edit, :update, :destroy]

  # GET /requests
  # GET /requests.json
  def index
      

      #current = Time.now
      #expired = Request.where(["expire_in < ?", current]).select(:meter_id)
      #blk = Meter.where("id IN (?) ", expired).select(:block_id)
      #b = Block.where("id IN (?)", blk)
      #b.each do |block|
      #  c = block.count
      #  if (c > 0)
      #    block.count = c - 1
      #  end
      #  block.save
      #end

      #Request.delete_all(["meter_id IN (?)", expired])

      ####


      #block = Block.joins(:meters).where(meters: { meter_id: meter_id})
      #puts block.inspect
    
      @requests = Request.where("expire_in > ?", Time.now)
      #@requests = Request.all
  end

  # GET /requests/1
  # GET /requests/1.json
  def show
  end

  # GET /requests/new
  def new
    @request = Request.new
  end

  # GET /requests/1/edit
  def edit
  end

  # POST /requests
  # POST /requests.json
  def create
    puts request_params.inspect
    @request = Request.new(request_params)

    respond_to do |format|
      if @request.save
        format.html { redirect_to @request, notice: 'Request was successfully created.' }
        format.json { render action: 'show', status: :created, location: @request }
      else
        format.html { render action: 'new' }
        format.json { render json: @request.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /requests/1
  # PATCH/PUT /requests/1.json
  def update
    respond_to do |format|
      if @request.update(request_params)
        format.html { redirect_to @request, notice: 'Request was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @request.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /requests/1
  # DELETE /requests/1.json
  def destroy
    @request.destroy
    respond_to do |format|
      format.html { redirect_to requests_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_request
      @request = Request.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def request_params
      params.require(:request).permit(:meter_id, :paytime, :duration, :expire_in, :status)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blocks_helper.rb
module BlocksHelper
end

app/helpers/meters_helper.rb
module MetersHelper
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/views/blocks/_form.html.erb
<%= form_for(@block) do |f| %>
  <% if @block.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@block.errors.count, "error") %> prohibited this block from being saved:</h2>

      <ul>
      <% @block.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :lat %><br>
    <%= f.text_field :lat %>
  </div>
  <div class="field">
    <%= f.label :lon %><br>
    <%= f.text_field :lon %>
  </div>
  <div class="field">
    <%= f.label :rate %><br>
    <%= f.text_field :rate %>
  </div>
  <div class="field">
    <%= f.label :limit %><br>
    <%= f.number_field :limit %>
  </div>
  <div class="field">
    <%= f.label :count %><br>
    <%= f.number_field :count %>
  </div>
  <div class="field">
    <%= f.label :fromDay %><br>
    <%= f.number_field :fromDay %>
  </div>
  <div class="field">
    <%= f.label :toDay %><br>
    <%= f.number_field :toDay %>
  </div>
  <div class="field">
    <%= f.label :fromHour %><br>
    <%= f.number_field :fromHour %>
  </div>
  <div class="field">
    <%= f.label :toHour %><br>
    <%= f.number_field :toHour %>
  </div>
  <div class="field">
    <%= f.label :status %><br>
    <%= f.number_field :status %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/blocks/edit.html.erb
<h1>Editing block</h1>

<%= render 'form' %>

<%= link_to 'Show', @block %> |
<%= link_to 'Back', blocks_path %>

app/views/blocks/index.html.erb
<h1>Listing blocks</h1>

<table>
  <thead>
    <tr>
      <th>Address</th>
      <th>Lat</th>
      <th>Lon</th>
      <th>Rate</th>
      <th>Limit</th>
      <th>Count</th>
      <th>Fromday</th>
      <th>Today</th>
      <th>Fromhour</th>
      <th>Tohour</th>
      <th>Status</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @blocks.each do |block| %>
      <tr>
        <td><%= block.address %></td>
        <td><%= block.lat %></td>
        <td><%= block.lon %></td>
        <td><%= block.rate %></td>
        <td><%= block.limit %></td>
        <td><%= block.count %></td>
        <td><%= block.fromDay %></td>
        <td><%= block.toDay %></td>
        <td><%= block.fromHour %></td>
        <td><%= block.toHour %></td>
        <td><%= block.status %></td>
        <td><%= link_to 'Show', block %></td>
        <td><%= link_to 'Edit', edit_block_path(block) %></td>
        <td><%= link_to 'Destroy', block, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Block', new_block_path %>

app/views/blocks/new.html.erb
<h1>New block</h1>

<%= render 'form' %>

<%= link_to 'Back', blocks_path %>

app/views/blocks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Address:</strong>
  <%= @block.address %>
</p>

<p>
  <strong>Limit:</strong>
  <%= @block.limit %>
</p>

<p>
  <strong>Count:</strong>
  <%= @block.count %>
</p>

<p>
  <strong>Fromday:</strong>
  <%= @block.fromDay %>
</p>

<p>
  <strong>Today:</strong>
  <%= @block.toDay %>
</p>

<p>
  <strong>Fromhour:</strong>
  <%= @block.fromHour %>
</p>

<p>
  <strong>Tohour:</strong>
  <%= @block.toHour %>
</p>

<p>
  <strong>Status:</strong>
  <%= @block.status %>
</p>

<%= link_to 'Edit', edit_block_path(@block) %> |
<%= link_to 'Back', blocks_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>EzPark</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/meters/_form.html.erb
<%= form_for(@meter) do |f| %>
  <% if @meter.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@meter.errors.count, "error") %> prohibited this meter from being saved:</h2>

      <ul>
      <% @meter.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :lat %><br>
    <%= f.text_field :lat %>
  </div>
  <div class="field">
    <%= f.label :long %><br>
    <%= f.text_field :long %>
  </div>
  <div class="field">
    <%= f.label :block_id %><br>
    <%= f.number_field :block_id %>
  </div>
  <div class="field">
    <%= f.label :meter_number %><br>
    <%= f.text_field :meter_number %>
  </div>
  <div class="field">
    <%= f.label :rate %><br>
    <%= f.text_field :rate %>
  </div>
  <div class="field">
    <%= f.label :status %><br>
    <%= f.number_field :status %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/meters/edit.html.erb
<h1>Editing meter</h1>

<%= render 'form' %>

<%= link_to 'Show', @meter %> |
<%= link_to 'Back', meters_path %>

app/views/meters/index.html.erb
<h1>Listing meters</h1>

<table>
  <thead>
    <tr>
      <th>Lat</th>
      <th>Long</th>
      <th>Block</th>
      <th>Number</th>
      <th>Rate</th>
      <th>Status</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @meters.each do |meter| %>
      <tr>
        <td><%= meter.lat %></td>
        <td><%= meter.long %></td>
        <td><%= meter.block_id %></td>
        <td><%= meter.meter_number %></td>
        <td><%= meter.rate %></td>
        <td><%= meter.status %></td>
        <td><%= link_to 'Show', meter %></td>
        <td><%= link_to 'Edit', edit_meter_path(meter) %></td>
        <td><%= link_to 'Destroy', meter, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Meter', new_meter_path %>

app/views/meters/new.html.erb
<h1>New meter</h1>

<%= render 'form' %>

<%= link_to 'Back', meters_path %>

app/views/meters/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Lat:</strong>
  <%= @meter.lat %>
</p>

<p>
  <strong>Long:</strong>
  <%= @meter.long %>
</p>

<p>
  <strong>Block:</strong>
  <%= @meter.block_id %>
</p>

<p>
  <strong>Rate:</strong>
  <%= @meter.rate %>
</p>

<p>
  <strong>Status:</strong>
  <%= @meter.status %>
</p>

<%= link_to 'Edit', edit_meter_path(@meter) %> |
<%= link_to 'Back', meters_path %>

app/views/requests/_form.html.erb
<%= form_for(@request) do |f| %>
  <% if @request.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@request.errors.count, "error") %> prohibited this request from being saved:</h2>

      <ul>
      <% @request.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :meter_id %><br>
    <%= f.number_field :meter_id %>
  </div>
  <div class="field">
    <%= f.label :paytime %><br>
    <%= f.datetime_select :paytime %>
  </div>
  <div class="field">
    <%= f.label :duration %><br>
    <%= f.number_field :duration %>
  </div>
  <div class="field">
    <%= f.label :expire_in %><br>
    <%= f.datetime_select :expire_in %>
  </div>
  <div class="field">
    <%= f.label :status %><br>
    <%= f.number_field :status %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/requests/edit.html.erb
<h1>Editing request</h1>

<%= render 'form' %>

<%= link_to 'Show', @request %> |
<%= link_to 'Back', requests_path %>

app/views/requests/index.html.erb
<h1>Listing requests</h1>

<table>
  <thead>
    <tr>
      <th>Meter</th>
      <th>Paytime</th>
      <th>Duration</th>
      <th>Expire</th>
      <th>Status</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @requests.each do |request| %>
      <tr>
        <td><%= request.meter_id %></td>
        <td><%= request.paytime %></td>
        <td><%= request.duration %></td>
        <td><%= request.expire_in %></td>
        <td><%= request.status %></td>
        <td><%= link_to 'Show', request %></td>
        <td><%= link_to 'Edit', edit_request_path(request) %></td>
        <td><%= link_to 'Destroy', request, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Request', new_request_path %>

app/views/requests/new.html.erb
<h1>New request</h1>

<%= render 'form' %>

<%= link_to 'Back', requests_path %>

app/views/requests/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Meter:</strong>
  <%= @request.meter_id %>
</p>

<p>
  <strong>Paytime:</strong>
  <%= @request.paytime %>
</p>

<p>
  <strong>Duration:</strong>
  <%= @request.duration %>
</p>

<p>
  <strong>Status:</strong>
  <%= @request.status %>
</p>

<%= link_to 'Edit', edit_request_path(@request) %> |
<%= link_to 'Back', requests_path %>